// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7lYii82SzjdYgWTkIGuTxvEr-gkeDo_Q',
    appId: '1:631213541262:web:608ba6a2f3c39f0b5686df',
    messagingSenderId: '631213541262',
    projectId: 'fir-auth-project-a0162',
    authDomain: 'fir-auth-project-a0162.firebaseapp.com',
    storageBucket: 'fir-auth-project-a0162.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIpc7-rvsnFAr4fdBW9dFBvGyzfrn4CAg',
    appId: '1:631213541262:android:67133d7a38abab415686df',
    messagingSenderId: '631213541262',
    projectId: 'fir-auth-project-a0162',
    storageBucket: 'fir-auth-project-a0162.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNfhy4p_bo-8389DJpwu5CSCbSnr1fe2s',
    appId: '1:631213541262:ios:21e7c96cf882e9595686df',
    messagingSenderId: '631213541262',
    projectId: 'fir-auth-project-a0162',
    storageBucket: 'fir-auth-project-a0162.appspot.com',
    androidClientId: '631213541262-vgua7no9eelt5elm8ec3huic0lpavbf2.apps.googleusercontent.com',
    iosClientId: '631213541262-9jv7rdbn00ibivpt38faiqh0auphhb59.apps.googleusercontent.com',
    iosBundleId: 'com.mostafij.firebaseAuthenticationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNfhy4p_bo-8389DJpwu5CSCbSnr1fe2s',
    appId: '1:631213541262:ios:5c9b98b09a882bce5686df',
    messagingSenderId: '631213541262',
    projectId: 'fir-auth-project-a0162',
    storageBucket: 'fir-auth-project-a0162.appspot.com',
    androidClientId: '631213541262-vgua7no9eelt5elm8ec3huic0lpavbf2.apps.googleusercontent.com',
    iosClientId: '631213541262-hk4usminmkilav99muo6o42743jaq6sn.apps.googleusercontent.com',
    iosBundleId: 'com.mostafij.firebaseAuthenticationProject.RunnerTests',
  );
}
